### ISSUE TITLE
Setup for Production

### ISSUE THREAD

**Issue by WAVIFICATION** [cap-js/audit-logging#109]
Hi,

I wish to add @cap-js/audit-logging to my SAP CAP app; but on following the instructions as per guide, it throws error on deployment.

`Error: No or malformed credentials for \"audit-log\"","at AuditLog2RESTv2.init`

Steps followed:

1. Add annotations to existing schema
2. Create Audit Log Service _**Premium**_ service instance.
3. Add the following to the mta file
```
  - name: audit-logging
    # ------------------------------------------------------------
    type: org.cloudfoundry.existing-service
```
4. Build the app using mbt and deploy to CF

Kindly help.

**Comment by sjvans** [comment]
hi @WAVIFICATION 

did you also bind your app to the service instance? your mta snippet only declares the resource.

**Comment by sjvans** [comment]
stale
