### ISSUE TITLE
add support to supply user and timestamp by consumer

### ISSUE THREAD

**Issue by soccermax** [cap-js/audit-logging#64]
would be nice if we could adjust the following coding, proposal would be to check if `tenant, user, timestamp` is present in `req.data`. The data from the global `cds.context` should only be used if the data is not supplied via `req.data`.

FYI: @sjvans 

```js
    // add common audit log entry fields
    this.before('*', req => {
      const { tenant, user, timestamp: time } = cds.context
      Object.assign(req.data, { uuid: cds.utils.uuid(), tenant, user: user.id, time })
    })
```

**Comment by sjvans** [comment]
hi @soccermax 

do you have a specific use case in mind? we intentionally decided not to allow to provide custom values until there is a verified need.

**Comment by soccermax** [comment]
We do our own outboxing with the event-queue but I assume that this would not be very different from the persistent outbox approach from cds. The user in the context of the global cds as well as the timestamp does not match the reality of the user and timestamp before the outboxing. Outbox runs in the context of a technical user and the timestamp does not match anymore
