### ISSUE TITLE
audit-logging/srv/log2restv2.js does return undefined in case of success

### ISSUE THREAD

**Issue by soccermax** [cap-js/audit-logging#74]
```js
    try {
      await _post(url, data, { headers })
    } catch (err) {
      LOG._trace && LOG.trace('error during log send:', err)
      // 429 (rate limit) is not unrecoverable
      if (String(err.response?.statusCode).match(/^4\d\d$/) && err.response?.statusCode !== 429)
        err.unrecoverable = true
      throw err
    }
```
--> `_send` does not return anything. However, the `_post` function returns the body in case of a successful request. 
Would it be possible to return this to the caller?

**Comment by oklemenz2** [comment]
Still an issue?

**Comment by sjvans** [comment]
> Still an issue?

@soccermax? ;)

**Comment by soccermax** [comment]
I'm fine without it, my intention was: that the REST API of the audit-log service returns an ID and some more info in the return structure of the create request, might be useful to have this information

**Comment by sjvans** [comment]
i'll keep in mind for the next iteration
