### ISSUE TITLE
audit-logging/srv/log2restv2.js - circular dependency in error case

### ISSUE THREAD

**Issue by soccermax** [cap-js/audit-logging#75]
```js
      res.on('end', () => {
        let body = Buffer.concat(chunks).toString()
        if (res.headers['content-type']?.match(/json/)) body = JSON.parse(body)
        if (res.statusCode >= 400) {
          const err = new Error(res.statusMessage)
          err.response = res
          err.body = body
          reject(err)
        } else {
          resolve(body)
        }
      })
```

err.response --> contains circular dependencies. This results in an error if we try to log the error.

![image](https://github.com/cap-js/audit-logging/assets/18613510/7a0d0976-f5a9-46d0-a1aa-2d6494e9fc60)

**Comment by oklemenz2** [comment]
Any update, when this will be implemented? `err` should be serializable ...

**Comment by sjvans** [comment]
hi @soccermax @oklemenz2 

imho a logger should be able to deal with circular jsons. or in other words: you shouldn't (have to) worry about what a/ your logger can deal with when constructing errors... but the circular structure in this case doesn't contain any important information other than maybe request url, etc., which we can add to the error directly, which should solve your issue while also reducing clutter.

best,
sebastian
