### ISSUE TITLE
Audit Log not working in Multitenancy

### ISSUE THREAD

**Issue by sanjayduttpandey** [cap-js/audit-logging#83]
Hi,

 I am implementing Audit-log for one of my project using [@cap-js/audit-logging](https://www.npmjs.com/package/@cap-js/audit-logging). It is working fine for dedicated tenant. But in case of SaaS app, its not working.
As per standard document, We need to do following configuration for Saas app.

**When providing an SaaS application, return the xsappname of the service instance's UAA instance (cds.env.requires['audit-log'].credentials.uaa.xsappname) as a dependency of your SaaS application,** see [SaaS Service Dependencies](https://pages.github.tools.sap/cap/docs/guides/deployment/to-cf#add-multitenancy).

Could you please provide sample how to add cds.env.requires['audit-log'].credentials.uaa.xsappname in package.json as SaaS dependency.

Thanks

**Comment by johannes-vogel** [comment]
Hi,

it's documented here: https://cap.cloud.sap/docs/guides/multitenancy/mtxs#saas-provisioning-config

Best,
Johannes
